# Generated by Django 4.2.23 on 2025-09-02 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("verbal_reasoning", "Verbal Reasoning"),
                            ("numerical_reasoning", "Numerical Reasoning"),
                            ("logical_reasoning", "Logical Reasoning"),
                            ("abstract_reasoning", "Abstract Reasoning"),
                            ("technical", "Technical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("duration_minutes", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                ("passing_score", models.IntegerField(default=70)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["test_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("current_question", models.IntegerField(default=1)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("answers", models.JSONField(default=dict)),
                ("time_spent", models.IntegerField(default=0)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testsengine.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
                "unique_together": {("user", "test")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("reading_comprehension", "Reading Comprehension"),
                            ("vocabulary", "Vocabulary in Context"),
                            ("logical_deduction", "Logical Deduction from Text"),
                            ("critical_reasoning", "Critical Reasoning"),
                            ("analogies", "Analogies and Relationships"),
                            ("multiple_choice", "Multiple Choice"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question_text", models.TextField()),
                ("passage", models.TextField(blank=True, null=True)),
                ("context", models.TextField(blank=True, null=True)),
                ("options", models.JSONField()),
                ("correct_answer", models.CharField(max_length=10)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="testsengine.test",
                    ),
                ),
            ],
            options={
                "ordering": ["test", "order"],
            },
        ),
        migrations.CreateModel(
            name="TestAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_answer", models.CharField(max_length=10)),
                ("is_correct", models.BooleanField()),
                ("time_taken", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testsengine.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_answers",
                        to="testsengine.testsession",
                    ),
                ),
            ],
            options={
                "ordering": ["question__order"],
                "unique_together": {("session", "question")},
            },
        ),
    ]
