# Generated by Django 5.1.7 on 2025-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsengine", "0002_auto_20250902_1718"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="base_image_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="complexity_score",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="main_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="option_remap",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="overlay_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="sequence_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="transforms",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="visual_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technical_3d", "Technical 3D Render"),
                    ("diagram", "Technical Diagram"),
                    ("wireframe", "Wireframe"),
                    ("isometric", "Isometric View"),
                    ("orthographic", "Orthographic Projection"),
                ],
                default="technical_3d",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("reading_comprehension", "Reading Comprehension"),
                    ("vocabulary", "Vocabulary in Context"),
                    ("logical_deduction", "Logical Deduction from Text"),
                    ("critical_reasoning", "Critical Reasoning"),
                    ("analogies", "Analogies and Relationships"),
                    ("mental_rotation", "Mental Rotation"),
                    ("paper_folding", "Paper Folding/Unfolding"),
                    ("cross_sections", "Cross-sections Identification"),
                    ("spatial_transformation", "Spatial Transformation"),
                    ("perspective_changes", "Perspective Changes"),
                    ("multiple_choice", "Multiple Choice"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("verbal_reasoning", "Verbal Reasoning"),
                    ("numerical_reasoning", "Numerical Reasoning"),
                    ("logical_reasoning", "Logical Reasoning"),
                    ("abstract_reasoning", "Abstract Reasoning"),
                    ("spatial_reasoning", "Spatial Reasoning"),
                    ("technical", "Technical"),
                ],
                max_length=50,
            ),
        ),
    ]
