# Generated by Django 4.2.24 on 2025-09-10 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testsengine", "0005_alter_codingsubmission_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codingsubmission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.CharField(db_index=True, max_length=64)),
                (
                    "test_version",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("language", models.CharField(default="en", max_length=8)),
                ("total_questions", models.PositiveIntegerField()),
                ("correct", models.PositiveIntegerField()),
                ("percentage", models.PositiveIntegerField()),
                ("raw_score", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("completed", "completed"),
                            ("aborted", "aborted"),
                            ("timeout", "timeout"),
                        ],
                        default="completed",
                        max_length=16,
                    ),
                ),
                (
                    "result_label",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "test_id", "created_at"],
                        name="testsengine_user_id_5dc22b_idx",
                    )
                ],
            },
        ),
    ]
