# Generated by Django 4.2.24 on 2025-09-19 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testsengine", "0009_database_optimization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsubmission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
