# Generated by Django 4.2.24 on 2025-09-22 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testsengine", "0010_allow_anonymous_submissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.TextField()),
                (
                    "score_value",
                    models.IntegerField(
                        help_text="Score: +2 (Best), +1 (Acceptable), 0 (Unacceptable), -1 (Must Not Choose)"
                    ),
                ),
                (
                    "option_letter",
                    models.CharField(help_text="A, B, C, D", max_length=1),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_options",
                        to="testsengine.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Option",
                "verbose_name_plural": "Question Options",
                "db_table": "testsengine_questionoption",
                "ordering": ["question", "option_letter"],
            },
        ),
    ]
