# Generated by Django 4.2.24 on 2025-09-22 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testsengine", "0011_questionoption"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestHistory",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "percentage_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("correct_answers", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("date_taken", models.DateTimeField(auto_now_add=True)),
                ("duration_minutes", models.IntegerField(default=0)),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Store user's answers and test metadata"
                    ),
                ),
                ("is_completed", models.BooleanField(default=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entry",
                        to="testsengine.testsubmission",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_sessions",
                        to="testsengine.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test History",
                "verbose_name_plural": "Test History",
                "ordering": ["-date_taken"],
                "indexes": [
                    models.Index(
                        fields=["user", "date_taken"],
                        name="testsengine_user_id_7c9259_idx",
                    ),
                    models.Index(
                        fields=["test", "date_taken"],
                        name="testsengine_test_id_fe2853_idx",
                    ),
                    models.Index(
                        fields=["user", "test", "date_taken"],
                        name="testsengine_user_id_840a87_idx",
                    ),
                ],
            },
        ),
    ]
