# Generated by Django 4.2.24 on 2025-09-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testsengine", "0012_testhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestHistory",
        ),
    ]
