# Generated by Django 4.2.24 on 2025-09-29 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testsengine", "0013_delete_testhistory"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testsession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="testsession",
            name="attempt_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Attempt number for this test"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testsession",
            unique_together={("user", "test", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="testsession",
            index=models.Index(
                fields=["user", "test", "-start_time"],
                name="testsengine_user_id_c2a1d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testsession",
            index=models.Index(
                fields=["user", "-start_time"], name="testsengine_user_id_25733c_idx"
            ),
        ),
    ]
