# Generated by Django 4.2.24 on 2025-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testsengine", "0014_add_attempt_number_to_testsession"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="testsubmission",
            name="unique_user_test_submission",
        ),
        migrations.AddIndex(
            model_name="testsubmission",
            index=models.Index(
                fields=["user", "test", "-submitted_at"],
                name="testsengine_user_id_ba58e6_idx",
            ),
        ),
    ]
