# Generated by Django 4.2.24 on 2025-09-26 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('category', models.CharField(choices=[('programming', 'Langages de programmation'), ('frontend', 'Technologies frontend'), ('backend', 'Technologies backend'), ('database', 'Bases de données'), ('devops', 'DevOps'), ('mobile', 'Développement mobile'), ('testing', 'Tests et QA'), ('other', 'Autres')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='Nom du test')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('total_score', models.IntegerField(verbose_name='Score total')),
                ('time_limit', models.IntegerField(help_text='Durée en minutes', verbose_name='Durée limite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('json_data', models.JSONField(blank=True, help_text='Collez votre JSON de test ici pour import automatique', null=True, verbose_name='Données JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill', verbose_name='Compétence')),
            ],
            options={
                'verbose_name': 'Test Technique',
                'verbose_name_plural': 'Tests Techniques',
                'ordering': ['skill__category', 'skill__name', 'test_name'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Ordre')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('option_a', models.CharField(max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Option D')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Réponse correcte')),
                ('points', models.IntegerField(default=1, verbose_name='Points')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.technicaltest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Question de Test',
                'verbose_name_plural': 'Questions de Test',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('skills_with_proficiency', models.JSONField(blank=True, default=list, verbose_name='Compétences avec niveau')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('skills', models.ManyToManyField(blank=True, to='skills.skill', verbose_name='Compétences')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Candidat',
                'verbose_name_plural': 'Profils Candidats',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('answers_data', models.JSONField(verbose_name='Données des réponses')),
                ('time_taken', models.IntegerField(help_text='Temps en secondes', verbose_name='Temps pris')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('abandoned', 'Abandonné')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.candidateprofile', verbose_name='Candidat')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.technicaltest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Résultat de Test',
                'verbose_name_plural': 'Résultats de Tests',
                'ordering': ['-started_at'],
                'unique_together': {('candidate', 'test')},
            },
        ),
    ]
