# Generated by Django 4.2.24 on 2025-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Photo de profil'),
        ),
    ]
