# Generated by Django 4.2.24 on 2025-09-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_candidateprofile_bio_candidateprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='skills_with_proficiency',
            field=models.JSONField(blank=True, default=list, verbose_name='Compétences avec niveau'),
        ),
    ]
