# Generated by Django 4.2.24 on 2025-09-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_add_enhanced_profile_models"),
        ("skills", "0003_candidateprofile_skills_with_proficiency"),
    ]

    operations = []
