# Generated by Django 4.2.24 on 2025-09-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecommendationdetail',
            name='location_score',
            field=models.FloatField(default=0.0, help_text='Location match score (0-100)'),
        ),
        migrations.AddField(
            model_name='jobrecommendationdetail',
            name='passed_tests',
            field=models.IntegerField(default=0, help_text='Number of tests passed'),
        ),
        migrations.AddField(
            model_name='jobrecommendationdetail',
            name='technical_test_score',
            field=models.FloatField(default=0.0, help_text='Technical test score (0-100)'),
        ),
        migrations.AddField(
            model_name='jobrecommendationdetail',
            name='test_proportion',
            field=models.FloatField(default=0.0, help_text='Proportion of tests passed (0-1)'),
        ),
        migrations.AddField(
            model_name='jobrecommendationdetail',
            name='total_relevant_tests',
            field=models.IntegerField(default=0, help_text='Total relevant tests for this job'),
        ),
        migrations.AddField(
            model_name='scoringweights',
            name='location_weight',
            field=models.FloatField(default=0.2, help_text='Weight for location match (20%)'),
        ),
        migrations.AddField(
            model_name='scoringweights',
            name='technical_test_weight',
            field=models.FloatField(default=0.3, help_text='Weight for technical test score (30%)'),
        ),
        migrations.AlterField(
            model_name='scoringweights',
            name='cluster_fit_weight',
            field=models.FloatField(default=0.0, help_text='Weight for cluster fit score (disabled)'),
        ),
        migrations.AlterField(
            model_name='scoringweights',
            name='content_similarity_weight',
            field=models.FloatField(default=0.0, help_text='Weight for content similarity score (disabled)'),
        ),
        migrations.AlterField(
            model_name='scoringweights',
            name='skill_match_weight',
            field=models.FloatField(default=0.5, help_text='Weight for skill matching score (50%)'),
        ),
    ]
