# Generated by Django 4.2.24 on 2025-09-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0002_enhanced_cognitive_recommendation_system"),
        ("recommendation", "0004_auto_20250925_0816"),
    ]

    operations = []
