# Generated by Django 4.2.24 on 2025-09-29 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_merge_20250929_0211"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recommendation", "0006_add_cognitive_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_id", models.IntegerField()),
                ("old_overall_score", models.FloatField(blank=True, null=True)),
                ("new_overall_score", models.FloatField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        help_text="Reason for change: weights_updated, new_test_result, etc.",
                        max_length=200,
                    ),
                ),
                ("algorithm_version", models.CharField(blank=True, max_length=50)),
                ("weights_snapshot_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Recommendation Audit",
                "verbose_name_plural": "Recommendation Audits",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="joboffer",
            options={
                "ordering": ["-posted_at"],
                "verbose_name": "Job Offer",
                "verbose_name_plural": "Job Offers",
            },
        ),
        migrations.AlterModelOptions(
            name="jobrecommendation",
            options={
                "ordering": ["-overall_score", "-computed_at"],
                "verbose_name": "Job Recommendation",
                "verbose_name_plural": "Job Recommendations",
            },
        ),
        migrations.AlterModelOptions(
            name="userjobpreference",
            options={
                "verbose_name": "User Job Preference",
                "verbose_name_plural": "User Job Preferences",
            },
        ),
        migrations.RemoveConstraint(
            model_name="savedjob",
            name="unique_user_job",
        ),
        migrations.RemoveConstraint(
            model_name="skilltechnicaltestmapping",
            name="unique_skill_technical_test",
        ),
        migrations.AlterUniqueTogether(
            name="jobrecommendation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="responsibilities",
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="salary_currency",
        ),
        migrations.RemoveField(
            model_name="scoringweights",
            name="salary_fit_weight",
        ),
        migrations.RemoveField(
            model_name="userjobpreference",
            name="accepts_remote",
        ),
        migrations.RemoveField(
            model_name="userjobpreference",
            name="max_recommendations",
        ),
        migrations.RemoveField(
            model_name="userjobpreference",
            name="min_score_threshold",
        ),
        migrations.RemoveField(
            model_name="userjobpreference",
            name="preferred_cities",
        ),
        migrations.RemoveField(
            model_name="userjobpreference",
            name="preferred_countries",
        ),
        migrations.RemoveField(
            model_name="userjobpreference",
            name="preferred_skills",
        ),
        migrations.RemoveField(
            model_name="userjobpreference",
            name="salary_currency",
        ),
        migrations.RemoveField(
            model_name="userjobpreference",
            name="skill_weights",
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="breakdown",
            field=models.JSONField(
                default=dict,
                help_text="Detailed breakdown: matched_skills, missing_skills, test_ids_and_scores, passed_ratio, etc.",
            ),
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="candidate_id",
            field=models.IntegerField(default=1, help_text="Candidate ID (User ID)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="cluster_fit_score",
            field=models.FloatField(
                default=0.0, help_text="K-Means cluster fit score (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="computed_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="experience_score",
            field=models.FloatField(
                default=0.0, help_text="Experience level match score (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="location_score",
            field=models.FloatField(
                default=0.0, help_text="Location match score (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="salary_score",
            field=models.FloatField(default=0.0, help_text="Salary fit score (0-1)"),
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="source_snapshot_id",
            field=models.CharField(
                blank=True, help_text="Source data snapshot ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="technical_test_score",
            field=models.FloatField(
                default=0.0, help_text="Technical test performance score (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="jobrecommendation",
            name="weights_snapshot_id",
            field=models.IntegerField(
                blank=True, help_text="ScoringWeights ID used", null=True
            ),
        ),
        migrations.AddField(
            model_name="userjobpreference",
            name="preferred_locations",
            field=models.JSONField(
                default=list, help_text="List of preferred cities/countries"
            ),
        ),
        migrations.AddField(
            model_name="userjobpreference",
            name="remote_preference",
            field=models.CharField(
                choices=[
                    ("remote", "Remote Only"),
                    ("hybrid", "Hybrid"),
                    ("office", "Office Only"),
                    ("flexible", "Flexible"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userjobpreference",
            name="skill_priorities",
            field=models.JSONField(default=dict, help_text="Skill importance weights"),
        ),
        migrations.AddField(
            model_name="userjobpreference",
            name="willing_to_relocate",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="company",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="company_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full Time"),
                    ("part-time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                ],
                default="full-time",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="posted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="preferred_skills",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_jobs", to="skills.skill"
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="remote_flag",
            field=models.BooleanField(default=False, help_text="Remote work available"),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="required_skills",
            field=models.ManyToManyField(
                blank=True, related_name="required_jobs", to="skills.skill"
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="seniority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("junior", "Junior"),
                    ("intermediate", "Intermediate"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                    ("principal", "Principal"),
                    ("expert", "Expert"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="jobrecommendation",
            name="algorithm_version",
            field=models.CharField(default="cognitive_kmeans_v1", max_length=50),
        ),
        migrations.AlterField(
            model_name="jobrecommendation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobrecommendation",
            name="job_offer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="recommendation.joboffer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobrecommendation",
            name="overall_score",
            field=models.FloatField(
                default=0.0, help_text="Overall recommendation score (0-1)"
            ),
        ),
        migrations.AlterField(
            model_name="jobrecommendation",
            name="skill_match_score",
            field=models.FloatField(
                default=0.0, help_text="Skill matching score (0-1)"
            ),
        ),
        migrations.AlterField(
            model_name="jobrecommendation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="jobrecommendationdetail",
            name="preferred_missing_skills",
            field=models.JSONField(
                default=list, help_text="Preferred skills that didn't match"
            ),
        ),
        migrations.AlterField(
            model_name="jobrecommendationdetail",
            name="required_missing_skills",
            field=models.JSONField(
                default=list, help_text="Required skills that didn't match"
            ),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="preferred_company_sizes",
            field=models.JSONField(default=list, help_text="Preferred company sizes"),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="preferred_industries",
            field=models.JSONField(default=list, help_text="Preferred industries"),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="preferred_job_types",
            field=models.JSONField(default=list, help_text="Preferred job types"),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="preferred_seniority",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="target_salary_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="target_salary_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userjobpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobrecommendation",
            unique_together={("candidate_id", "job_offer")},
        ),
        migrations.AlterUniqueTogether(
            name="savedjob",
            unique_together={("user", "job_id")},
        ),
        migrations.AlterUniqueTogether(
            name="skilltechnicaltestmapping",
            unique_together={("skill", "technical_test")},
        ),
        migrations.AddIndex(
            model_name="jobrecommendation",
            index=models.Index(
                fields=["candidate_id", "-overall_score"],
                name="recommendat_candida_19fe36_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobrecommendation",
            index=models.Index(
                fields=["job_offer", "-overall_score"],
                name="recommendat_job_off_c72958_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobrecommendation",
            index=models.Index(
                fields=["computed_at"], name="recommendat_compute_2562e6_idx"
            ),
        ),
        migrations.AddField(
            model_name="recommendationaudit",
            name="job_offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recommendation.joboffer",
            ),
        ),
        migrations.AddField(
            model_name="recommendationaudit",
            name="recommendation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_trail",
                to="recommendation.jobrecommendation",
            ),
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="cluster_id",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="job",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="location_match_score",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="matched_skills",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="missing_skills",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="recommendation_reason",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="remote_bonus",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="salary_fit_score",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="score",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="seniority_match_score",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="status",
        ),
        migrations.RemoveField(
            model_name="jobrecommendation",
            name="user",
        ),
    ]
